#pragma once

///////////////////////////////////////////////////////////////////////////////
//////////////////////////////// INCLUDES /////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

#include <array>
#include "Utils.hpp"
#include <gtest/gtest.h>
#include <gmock/gmock.h>

///////////////////////////////////////////////////////////////////////////////
/////////////////////////// CLASSES/STRUCTURES ////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

class UtilsFixture : public::testing::Test
{
    public:
        static constexpr char * Module = (char *)"UtilsMock";
        
        UtilsFixture () = default;
        ~UtilsFixture () = default;

        struct AsciToInt
        {
            struct ConversionResult
            {
                static constexpr std::pair <char, uint8_t> Positive [22] = { std::make_pair ('0', 0),
                                                                             std::make_pair ('1', 1),
                                                                             std::make_pair ('2', 2),
                                                                             std::make_pair ('3', 3),
                                                                             std::make_pair ('4', 4),
                                                                             std::make_pair ('5', 5),
                                                                             std::make_pair ('6', 6),
                                                                             std::make_pair ('7', 7),
                                                                             std::make_pair ('8', 8),
                                                                             std::make_pair ('9', 9),
                                                                             std::make_pair ('a', 10),
                                                                             std::make_pair ('b', 11),
                                                                             std::make_pair ('c', 12),
                                                                             std::make_pair ('d', 13),
                                                                             std::make_pair ('e', 14),
                                                                             std::make_pair ('f', 15),
                                                                             std::make_pair ('A', 10),
                                                                             std::make_pair ('B', 11),
                                                                             std::make_pair ('C', 12),
                                                                             std::make_pair ('D', 13),
                                                                             std::make_pair ('E', 14),
                                                                             std::make_pair ('F', 15) };

                static constexpr std::array <char, 10> Negative = { 'p',
                                                                    'G',
                                                                    'g',
                                                                    'X',
                                                                    'y',
                                                                    'Z',
                                                                    'l',
                                                                    ']',
                                                                    '/',
                                                                    ',' };
            } ConversionResult;
        } AsciToInt;

        struct
        {
            const std::pair <std::string, uint8_t> Positive [256] = { std::make_pair ("0x00", 0),
                                                                      std::make_pair ("0x01", 1),
                                                                      std::make_pair ("0x02", 2),
                                                                      std::make_pair ("0x03", 3),
                                                                      std::make_pair ("0x04", 4),
                                                                      std::make_pair ("0x05", 5),
                                                                      std::make_pair ("0x06", 6),
                                                                      std::make_pair ("0x07", 7),
                                                                      std::make_pair ("0x08", 8),
                                                                      std::make_pair ("0x09", 9),
                                                                      std::make_pair ("0x0A", 10),
                                                                      std::make_pair ("0x0B", 11),
                                                                      std::make_pair ("0x0C", 12),
                                                                      std::make_pair ("0x0D", 13),
                                                                      std::make_pair ("0x0E", 14),
                                                                      std::make_pair ("0x0F", 15),
                                                                      std::make_pair ("0x10", 16),
                                                                      std::make_pair ("0x11", 17),
                                                                      std::make_pair ("0x12", 18),
                                                                      std::make_pair ("0x13", 19),
                                                                      std::make_pair ("0x14", 20),
                                                                      std::make_pair ("0x15", 21),
                                                                      std::make_pair ("0x16", 22),
                                                                      std::make_pair ("0x17", 23),
                                                                      std::make_pair ("0x18", 24),
                                                                      std::make_pair ("0x19", 25),
                                                                      std::make_pair ("0x1A", 26),
                                                                      std::make_pair ("0x1B", 27),
                                                                      std::make_pair ("0x1C", 28),
                                                                      std::make_pair ("0x1D", 29),
                                                                      std::make_pair ("0x1E", 30),
                                                                      std::make_pair ("0x1F", 31),
                                                                      std::make_pair ("0x20", 32),
                                                                      std::make_pair ("0x21", 33),
                                                                      std::make_pair ("0x22", 34),
                                                                      std::make_pair ("0x23", 35),
                                                                      std::make_pair ("0x24", 36),
                                                                      std::make_pair ("0x25", 37),
                                                                      std::make_pair ("0x26", 38),
                                                                      std::make_pair ("0x27", 39),
                                                                      std::make_pair ("0x28", 40),
                                                                      std::make_pair ("0x29", 41),
                                                                      std::make_pair ("0x2A", 42),
                                                                      std::make_pair ("0x2B", 43),
                                                                      std::make_pair ("0x2C", 44),
                                                                      std::make_pair ("0x2D", 45),
                                                                      std::make_pair ("0x2E", 46),
                                                                      std::make_pair ("0x2F", 47),
                                                                      std::make_pair ("0x30", 48),
                                                                      std::make_pair ("0x31", 49),
                                                                      std::make_pair ("0x32", 50),
                                                                      std::make_pair ("0x33", 51),
                                                                      std::make_pair ("0x34", 52),
                                                                      std::make_pair ("0x35", 53),
                                                                      std::make_pair ("0x36", 54),
                                                                      std::make_pair ("0x37", 55),
                                                                      std::make_pair ("0x38", 56),
                                                                      std::make_pair ("0x39", 57),
                                                                      std::make_pair ("0x3A", 58),
                                                                      std::make_pair ("0x3B", 59),
                                                                      std::make_pair ("0x3C", 60),
                                                                      std::make_pair ("0x3D", 61),
                                                                      std::make_pair ("0x3E", 62),
                                                                      std::make_pair ("0x3F", 63),
                                                                      std::make_pair ("0x40", 64),
                                                                      std::make_pair ("0x41", 65),
                                                                      std::make_pair ("0x42", 66),
                                                                      std::make_pair ("0x43", 67),
                                                                      std::make_pair ("0x44", 68),
                                                                      std::make_pair ("0x45", 69),
                                                                      std::make_pair ("0x46", 70),
                                                                      std::make_pair ("0x47", 71),
                                                                      std::make_pair ("0x48", 72),
                                                                      std::make_pair ("0x49", 73),
                                                                      std::make_pair ("0x4A", 74),
                                                                      std::make_pair ("0x4B", 75),
                                                                      std::make_pair ("0x4C", 76),
                                                                      std::make_pair ("0x4D", 77),
                                                                      std::make_pair ("0x4E", 78),
                                                                      std::make_pair ("0x4F", 79),
                                                                      std::make_pair ("0x50", 80),
                                                                      std::make_pair ("0x51", 81),
                                                                      std::make_pair ("0x52", 82),
                                                                      std::make_pair ("0x53", 83),
                                                                      std::make_pair ("0x54", 84),
                                                                      std::make_pair ("0x55", 85),
                                                                      std::make_pair ("0x56", 86),
                                                                      std::make_pair ("0x57", 87),
                                                                      std::make_pair ("0x58", 88),
                                                                      std::make_pair ("0x59", 89),
                                                                      std::make_pair ("0x5A", 90),
                                                                      std::make_pair ("0x5B", 91),
                                                                      std::make_pair ("0x5C", 92),
                                                                      std::make_pair ("0x5D", 93),
                                                                      std::make_pair ("0x5E", 94),
                                                                      std::make_pair ("0x5F", 95),
                                                                      std::make_pair ("0x60", 96),
                                                                      std::make_pair ("0x61", 97),
                                                                      std::make_pair ("0x62", 98),
                                                                      std::make_pair ("0x63", 99),
                                                                      std::make_pair ("0x64", 100),
                                                                      std::make_pair ("0x65", 101),
                                                                      std::make_pair ("0x66", 102),
                                                                      std::make_pair ("0x67", 103),
                                                                      std::make_pair ("0x68", 104),
                                                                      std::make_pair ("0x69", 105),
                                                                      std::make_pair ("0x6A", 106),
                                                                      std::make_pair ("0x6B", 107),
                                                                      std::make_pair ("0x6C", 108),
                                                                      std::make_pair ("0x6D", 109),
                                                                      std::make_pair ("0x6E", 110),
                                                                      std::make_pair ("0x6F", 111),
                                                                      std::make_pair ("0x70", 112),
                                                                      std::make_pair ("0x71", 113),
                                                                      std::make_pair ("0x72", 114),
                                                                      std::make_pair ("0x73", 115),
                                                                      std::make_pair ("0x74", 116),
                                                                      std::make_pair ("0x75", 117),
                                                                      std::make_pair ("0x76", 118),
                                                                      std::make_pair ("0x77", 119),
                                                                      std::make_pair ("0x78", 120),
                                                                      std::make_pair ("0x79", 121),
                                                                      std::make_pair ("0x7A", 122),
                                                                      std::make_pair ("0x7B", 123),
                                                                      std::make_pair ("0x7C", 124),
                                                                      std::make_pair ("0x7D", 125),
                                                                      std::make_pair ("0x7E", 126),
                                                                      std::make_pair ("0x7F", 127),
                                                                      std::make_pair ("0x80", 128),
                                                                      std::make_pair ("0x81", 129),
                                                                      std::make_pair ("0x82", 130),
                                                                      std::make_pair ("0x83", 131),
                                                                      std::make_pair ("0x84", 132),
                                                                      std::make_pair ("0x85", 133),
                                                                      std::make_pair ("0x86", 134),
                                                                      std::make_pair ("0x87", 135),
                                                                      std::make_pair ("0x88", 136),
                                                                      std::make_pair ("0x89", 137),
                                                                      std::make_pair ("0x8A", 138),
                                                                      std::make_pair ("0x8B", 139),
                                                                      std::make_pair ("0x8C", 140),
                                                                      std::make_pair ("0x8D", 141),
                                                                      std::make_pair ("0x8E", 142),
                                                                      std::make_pair ("0x8F", 143),
                                                                      std::make_pair ("0x90", 144),
                                                                      std::make_pair ("0x91", 145),
                                                                      std::make_pair ("0x92", 146),
                                                                      std::make_pair ("0x93", 147),
                                                                      std::make_pair ("0x94", 148),
                                                                      std::make_pair ("0x95", 149),
                                                                      std::make_pair ("0x96", 150),
                                                                      std::make_pair ("0x97", 151),
                                                                      std::make_pair ("0x98", 152),
                                                                      std::make_pair ("0x99", 153),
                                                                      std::make_pair ("0x9A", 154),
                                                                      std::make_pair ("0x9B", 155),
                                                                      std::make_pair ("0x9C", 156),
                                                                      std::make_pair ("0x9D", 157),
                                                                      std::make_pair ("0x9E", 158),
                                                                      std::make_pair ("0x9F", 159),
                                                                      std::make_pair ("0xA0", 160),
                                                                      std::make_pair ("0xA1", 161),
                                                                      std::make_pair ("0xA2", 162),
                                                                      std::make_pair ("0xA3", 163),
                                                                      std::make_pair ("0xA4", 164),
                                                                      std::make_pair ("0xA5", 165),
                                                                      std::make_pair ("0xA6", 166),
                                                                      std::make_pair ("0xA7", 167),
                                                                      std::make_pair ("0xA8", 168),
                                                                      std::make_pair ("0xA9", 169),
                                                                      std::make_pair ("0xAA", 170),
                                                                      std::make_pair ("0xAB", 171),
                                                                      std::make_pair ("0xAC", 172),
                                                                      std::make_pair ("0xAD", 173),
                                                                      std::make_pair ("0xAE", 174),
                                                                      std::make_pair ("0xAF", 175),
                                                                      std::make_pair ("0xB0", 176),
                                                                      std::make_pair ("0xB1", 177),
                                                                      std::make_pair ("0xB2", 178),
                                                                      std::make_pair ("0xB3", 179),
                                                                      std::make_pair ("0xB4", 180),
                                                                      std::make_pair ("0xB5", 181),
                                                                      std::make_pair ("0xB6", 182),
                                                                      std::make_pair ("0xB7", 183),
                                                                      std::make_pair ("0xB8", 184),
                                                                      std::make_pair ("0xB9", 185),
                                                                      std::make_pair ("0xBA", 186),
                                                                      std::make_pair ("0xBB", 187),
                                                                      std::make_pair ("0xBC", 188),
                                                                      std::make_pair ("0xBD", 189),
                                                                      std::make_pair ("0xBE", 190),
                                                                      std::make_pair ("0xBF", 191),
                                                                      std::make_pair ("0xC0", 192),
                                                                      std::make_pair ("0xC1", 193),
                                                                      std::make_pair ("0xC2", 194),
                                                                      std::make_pair ("0xC3", 195),
                                                                      std::make_pair ("0xC4", 196),
                                                                      std::make_pair ("0xC5", 197),
                                                                      std::make_pair ("0xC6", 198),
                                                                      std::make_pair ("0xC7", 199),
                                                                      std::make_pair ("0xC8", 200),
                                                                      std::make_pair ("0xC9", 201),
                                                                      std::make_pair ("0xCA", 202),
                                                                      std::make_pair ("0xCB", 203),
                                                                      std::make_pair ("0xCC", 204),
                                                                      std::make_pair ("0xCD", 205),
                                                                      std::make_pair ("0xCE", 206),
                                                                      std::make_pair ("0xCF", 207),
                                                                      std::make_pair ("0xD0", 208),
                                                                      std::make_pair ("0xD1", 209),
                                                                      std::make_pair ("0xD2", 210),
                                                                      std::make_pair ("0xD3", 211),
                                                                      std::make_pair ("0xD4", 212),
                                                                      std::make_pair ("0xD5", 213),
                                                                      std::make_pair ("0xD6", 214),
                                                                      std::make_pair ("0xD7", 215),
                                                                      std::make_pair ("0xD8", 216),
                                                                      std::make_pair ("0xD9", 217),
                                                                      std::make_pair ("0xDA", 218),
                                                                      std::make_pair ("0xDB", 219),
                                                                      std::make_pair ("0xDC", 220),
                                                                      std::make_pair ("0xDD", 221),
                                                                      std::make_pair ("0xDE", 222),
                                                                      std::make_pair ("0xDF", 223),
                                                                      std::make_pair ("0xE0", 224),
                                                                      std::make_pair ("0xE1", 225),
                                                                      std::make_pair ("0xE2", 226),
                                                                      std::make_pair ("0xE3", 227),
                                                                      std::make_pair ("0xE4", 228),
                                                                      std::make_pair ("0xE5", 229),
                                                                      std::make_pair ("0xE6", 230),
                                                                      std::make_pair ("0xE7", 231),
                                                                      std::make_pair ("0xE8", 232),
                                                                      std::make_pair ("0xE9", 233),
                                                                      std::make_pair ("0xEA", 234),
                                                                      std::make_pair ("0xEB", 235),
                                                                      std::make_pair ("0xEC", 236),
                                                                      std::make_pair ("0xED", 237),
                                                                      std::make_pair ("0xEE", 238),
                                                                      std::make_pair ("0xEF", 239),
                                                                      std::make_pair ("0xF0", 240),
                                                                      std::make_pair ("0xF1", 241),
                                                                      std::make_pair ("0xF2", 242),
                                                                      std::make_pair ("0xF3", 243),
                                                                      std::make_pair ("0xF4", 244),
                                                                      std::make_pair ("0xF5", 245),
                                                                      std::make_pair ("0xF6", 246),
                                                                      std::make_pair ("0xF7", 247),
                                                                      std::make_pair ("0xF8", 248),
                                                                      std::make_pair ("0xF9", 249),
                                                                      std::make_pair ("0xFA", 250),
                                                                      std::make_pair ("0xFB", 251),
                                                                      std::make_pair ("0xFC", 252),
                                                                      std::make_pair ("0xFD", 253),
                                                                      std::make_pair ("0xFE", 254),
                                                                      std::make_pair ("0xFF", 255)
            };

            const std::array <std::string, 10> Negative = { "0xn@",
                                                            "0xG,",
                                                            "0xgu",
                                                            "0xXy",
                                                            "0xyt",
                                                            "0xZr",
                                                            "0xl,",
                                                            "0x]w",
                                                            "0x/q",
                                                            "0x,k" };
        } HexInAsciToIntConversionResult;
};

///////////////////////////////////////////////////////////////////////////////
/////////////////////////////// END OF FILE ///////////////////////////////////
///////////////////////////////////////////////////////////////////////////////