#pragma once

///////////////////////////////////////////////////////////////////////////////
//////////////////////////////// INCLUDES /////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

#include <array>
#include "Utils.h"
#include <gtest/gtest.h>
#include <gmock/gmock.h>

///////////////////////////////////////////////////////////////////////////////
/////////////////////////// CLASSES/STRUCTURES ////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

class UtilsFixture : public::testing::Test
{
    static constexpr char * MODULE = (char *)"UtilsMock";

    public:
        UtilsFixture () = default;
        ~UtilsFixture () = default;

        struct AsciToInt
        {
            struct ConversionResult
            {
                static constexpr std::pair <char, uint8_t> Positive [TWENTY_TWO] = { std::make_pair ('0', ZERO),
                                                                                     std::make_pair ('1', ONE),
                                                                                     std::make_pair ('2', TWO),
                                                                                     std::make_pair ('3', THREE),
                                                                                     std::make_pair ('4', FOUR),
                                                                                     std::make_pair ('5', FIVE),
                                                                                     std::make_pair ('6', SIX),
                                                                                     std::make_pair ('7', SEVEN),
                                                                                     std::make_pair ('8', EIGHT),
                                                                                     std::make_pair ('9', NINE),
                                                                                     std::make_pair ('a', TEN),
                                                                                     std::make_pair ('b', ELEVEN),
                                                                                     std::make_pair ('c', TWELVE),
                                                                                     std::make_pair ('d', THIRTEEN),
                                                                                     std::make_pair ('e', FOURTEEN),
                                                                                     std::make_pair ('f', FIFTEEN),
                                                                                     std::make_pair ('A', TEN),
                                                                                     std::make_pair ('B', ELEVEN),
                                                                                     std::make_pair ('C', TWELVE),
                                                                                     std::make_pair ('D', THIRTEEN),
                                                                                     std::make_pair ('E', FOURTEEN),
                                                                                     std::make_pair ('F', FIFTEEN) };

                static constexpr std::array <char, TEN> Negative                 = { 'p',
                                                                                     'G',
                                                                                     'g',
                                                                                     'X',
                                                                                     'y',
                                                                                     'Z',
                                                                                     'l',
                                                                                     ']',
                                                                                     '/',
                                                                                     ',' };
            } ConversionResult;
        } AsciToInt;

        struct
        {
            const std::pair <std::string, uint8_t> Positive [TWO_HUNDRED_FIFTY_SIX] = { std::make_pair ("0x00", ZERO),
                                                                                        std::make_pair ("0x01", ONE),
                                                                                        std::make_pair ("0x02", TWO),
                                                                                        std::make_pair ("0x03", THREE),
                                                                                        std::make_pair ("0x04", FOUR),
                                                                                        std::make_pair ("0x05", FIVE),
                                                                                        std::make_pair ("0x06", SIX),
                                                                                        std::make_pair ("0x07", SEVEN),
                                                                                        std::make_pair ("0x08", EIGHT),
                                                                                        std::make_pair ("0x09", NINE),
                                                                                        std::make_pair ("0x0A", TEN),
                                                                                        std::make_pair ("0x0B", ELEVEN),
                                                                                        std::make_pair ("0x0C", TWELVE),
                                                                                        std::make_pair ("0x0D", THIRTEEN),
                                                                                        std::make_pair ("0x0E", FOURTEEN),
                                                                                        std::make_pair ("0x0F", FIFTEEN),
                                                                                        std::make_pair ("0x10", SIXTEEN),
                                                                                        std::make_pair ("0x11", SEVENTEEN),
                                                                                        std::make_pair ("0x12", EIGHTEEN),
                                                                                        std::make_pair ("0x13", NINETEEN),
                                                                                        std::make_pair ("0x14", TWENTY),
                                                                                        std::make_pair ("0x15", TWENTY_ONE),
                                                                                        std::make_pair ("0x16", TWENTY_TWO),
                                                                                        std::make_pair ("0x17", TWENTY_THREE),
                                                                                        std::make_pair ("0x18", TWENTY_FOUR),
                                                                                        std::make_pair ("0x19", TWENTY_FIVE),
                                                                                        std::make_pair ("0x1A", TWENTY_SIX),
                                                                                        std::make_pair ("0x1B", TWENTY_SEVEN),
                                                                                        std::make_pair ("0x1C", TWENTY_EIGHT),
                                                                                        std::make_pair ("0x1D", TWENTY_NINE),
                                                                                        std::make_pair ("0x1E", THIRTY),
                                                                                        std::make_pair ("0x1F", THIRTY_ONE),
                                                                                        std::make_pair ("0x20", THIRTY_TWO),
                                                                                        std::make_pair ("0x21", THIRTY_THREE),
                                                                                        std::make_pair ("0x22", THIRTY_FOUR),
                                                                                        std::make_pair ("0x23", THIRTY_FIVE),
                                                                                        std::make_pair ("0x24", THIRTY_SIX),
                                                                                        std::make_pair ("0x25", THIRTY_SEVEN),
                                                                                        std::make_pair ("0x26", THIRTY_EIGHT),
                                                                                        std::make_pair ("0x27", THIRTY_NINE),
                                                                                        std::make_pair ("0x28", FORTY),
                                                                                        std::make_pair ("0x29", FORTY_ONE),
                                                                                        std::make_pair ("0x2A", FORTY_TWO),
                                                                                        std::make_pair ("0x2B", FORTY_THREE),
                                                                                        std::make_pair ("0x2C", FORTY_FOUR),
                                                                                        std::make_pair ("0x2D", FORTY_FIVE),
                                                                                        std::make_pair ("0x2E", FORTY_SIX),
                                                                                        std::make_pair ("0x2F", FORTY_SEVEN),
                                                                                        std::make_pair ("0x30", FORTY_EIGHT),
                                                                                        std::make_pair ("0x31", FORTY_NINE),
                                                                                        std::make_pair ("0x32", FIFTY),
                                                                                        std::make_pair ("0x33", FIFTY_ONE),
                                                                                        std::make_pair ("0x34", FIFTY_TWO),
                                                                                        std::make_pair ("0x35", FIFTY_THREE),
                                                                                        std::make_pair ("0x36", FIFTY_FOUR),
                                                                                        std::make_pair ("0x37", FIFTY_FIVE),
                                                                                        std::make_pair ("0x38", FIFTY_SIX),
                                                                                        std::make_pair ("0x39", FIFTY_SEVEN),
                                                                                        std::make_pair ("0x3A", FIFTY_EIGHT),
                                                                                        std::make_pair ("0x3B", FIFTY_NINE),
                                                                                        std::make_pair ("0x3C", SIXTY),
                                                                                        std::make_pair ("0x3D", SIXTY_ONE),
                                                                                        std::make_pair ("0x3E", SIXTY_TWO),
                                                                                        std::make_pair ("0x3F", SIXTY_THREE),
                                                                                        std::make_pair ("0x40", SIXTY_FOUR),
                                                                                        std::make_pair ("0x41", SIXTY_FIVE),
                                                                                        std::make_pair ("0x42", SIXTY_SIX),
                                                                                        std::make_pair ("0x43", SIXTY_SEVEN),
                                                                                        std::make_pair ("0x44", SIXTY_EIGHT),
                                                                                        std::make_pair ("0x45", SIXTY_NINE),
                                                                                        std::make_pair ("0x46", SEVENTY),
                                                                                        std::make_pair ("0x47", SEVENTY_ONE),
                                                                                        std::make_pair ("0x48", SEVENTY_TWO),
                                                                                        std::make_pair ("0x49", SEVENTY_THREE),
                                                                                        std::make_pair ("0x4A", SEVENTY_FOUR),
                                                                                        std::make_pair ("0x4B", SEVENTY_FIVE),
                                                                                        std::make_pair ("0x4C", SEVENTY_SIX),
                                                                                        std::make_pair ("0x4D", SEVENTY_SEVEN),
                                                                                        std::make_pair ("0x4E", SEVENTY_EIGHT),
                                                                                        std::make_pair ("0x4F", SEVENTY_NINE),
                                                                                        std::make_pair ("0x50", EIGHTY),
                                                                                        std::make_pair ("0x51", EIGHTY_ONE),
                                                                                        std::make_pair ("0x52", EIGHTY_TWO),
                                                                                        std::make_pair ("0x53", EIGHTY_THREE),
                                                                                        std::make_pair ("0x54", EIGHTY_FOUR),
                                                                                        std::make_pair ("0x55", EIGHTY_FIVE),
                                                                                        std::make_pair ("0x56", EIGHTY_SIX),
                                                                                        std::make_pair ("0x57", EIGHTY_SEVEN),
                                                                                        std::make_pair ("0x58", EIGHTY_EIGHT),
                                                                                        std::make_pair ("0x59", EIGHTY_NINE),
                                                                                        std::make_pair ("0x5A", NINTY),
                                                                                        std::make_pair ("0x5B", NINTY_ONE),
                                                                                        std::make_pair ("0x5C", NINTY_TWO),
                                                                                        std::make_pair ("0x5D", NINTY_THREE),
                                                                                        std::make_pair ("0x5E", NINTY_FOUR),
                                                                                        std::make_pair ("0x5F", NINTY_FIVE),
                                                                                        std::make_pair ("0x60", NINTY_SIX),
                                                                                        std::make_pair ("0x61", NINTY_SEVEN),
                                                                                        std::make_pair ("0x62", NINTY_EIGHT),
                                                                                        std::make_pair ("0x63", NINTY_NINE),
                                                                                        std::make_pair ("0x64", ONE_HUNDRED),
                                                                                        std::make_pair ("0x65", ONE_HUNDRED_ONE),
                                                                                        std::make_pair ("0x66", ONE_HUNDRED_TWO),
                                                                                        std::make_pair ("0x67", ONE_HUNDRED_THREE),
                                                                                        std::make_pair ("0x68", ONE_HUNDRED_FOUR),
                                                                                        std::make_pair ("0x69", ONE_HUNDRED_FIVE),
                                                                                        std::make_pair ("0x6A", ONE_HUNDRED_SIX),
                                                                                        std::make_pair ("0x6B", ONE_HUNDRED_SEVEN),
                                                                                        std::make_pair ("0x6C", ONE_HUNDRED_EIGHT),
                                                                                        std::make_pair ("0x6D", ONE_HUNDRED_NINE),
                                                                                        std::make_pair ("0x6E", ONE_HUNDRED_TEN),
                                                                                        std::make_pair ("0x6F", ONE_HUNDRED_ELEVEN),
                                                                                        std::make_pair ("0x70", ONE_HUNDRED_TWELVE),
                                                                                        std::make_pair ("0x71", ONE_HUNDRED_THIRTEEN),
                                                                                        std::make_pair ("0x72", ONE_HUNDRED_FOURTEEN),
                                                                                        std::make_pair ("0x73", ONE_HUNDRED_FIFTEEN),
                                                                                        std::make_pair ("0x74", ONE_HUNDRED_SIXTEEN),
                                                                                        std::make_pair ("0x75", ONE_HUNDRED_SEVENTEEN),
                                                                                        std::make_pair ("0x76", ONE_HUNDRED_EIGHTEEN),
                                                                                        std::make_pair ("0x77", ONE_HUNDRED_NINETEEN),
                                                                                        std::make_pair ("0x78", ONE_HUNDRED_TWENTY),
                                                                                        std::make_pair ("0x79", ONE_HUNDRED_TWENTY_ONE),
                                                                                        std::make_pair ("0x7A", ONE_HUNDRED_TWENTY_TWO),
                                                                                        std::make_pair ("0x7B", ONE_HUNDRED_TWENTY_THREE),
                                                                                        std::make_pair ("0x7C", ONE_HUNDRED_TWENTY_FOUR),
                                                                                        std::make_pair ("0x7D", ONE_HUNDRED_TWENTY_FIVE),
                                                                                        std::make_pair ("0x7E", ONE_HUNDRED_TWENTY_SIX),
                                                                                        std::make_pair ("0x7F", ONE_HUNDRED_TWENTY_SEVEN),
                                                                                        std::make_pair ("0x80", ONE_HUNDRED_TWENTY_EIGHT),
                                                                                        std::make_pair ("0x81", ONE_HUNDRED_TWENTY_NINE),
                                                                                        std::make_pair ("0x82", ONE_HUNDRED_THIRTY),
                                                                                        std::make_pair ("0x83", ONE_HUNDRED_THIRTY_ONE),
                                                                                        std::make_pair ("0x84", ONE_HUNDRED_THIRTY_TWO),
                                                                                        std::make_pair ("0x85", ONE_HUNDRED_THIRTY_THREE),
                                                                                        std::make_pair ("0x86", ONE_HUNDRED_THIRTY_FOUR),
                                                                                        std::make_pair ("0x87", ONE_HUNDRED_THIRTY_FIVE),
                                                                                        std::make_pair ("0x88", ONE_HUNDRED_THIRTY_SIX),
                                                                                        std::make_pair ("0x89", ONE_HUNDRED_THIRTY_SEVEN),
                                                                                        std::make_pair ("0x8A", ONE_HUNDRED_THIRTY_EIGHT),
                                                                                        std::make_pair ("0x8B", ONE_HUNDRED_THIRTY_NINE),
                                                                                        std::make_pair ("0x8C", ONE_HUNDRED_FORTY),
                                                                                        std::make_pair ("0x8D", ONE_HUNDRED_FORTY_ONE),
                                                                                        std::make_pair ("0x8E", ONE_HUNDRED_FORTY_TWO),
                                                                                        std::make_pair ("0x8F", ONE_HUNDRED_FORTY_THREE),
                                                                                        std::make_pair ("0x90", ONE_HUNDRED_FORTY_FOUR),
                                                                                        std::make_pair ("0x91", ONE_HUNDRED_FORTY_FIVE),
                                                                                        std::make_pair ("0x92", ONE_HUNDRED_FORTY_SIX),
                                                                                        std::make_pair ("0x93", ONE_HUNDRED_FORTY_SEVEN),
                                                                                        std::make_pair ("0x94", ONE_HUNDRED_FORTY_EIGHT),
                                                                                        std::make_pair ("0x95", ONE_HUNDRED_FORTY_NINE),
                                                                                        std::make_pair ("0x96", ONE_HUNDRED_FIFTY),
                                                                                        std::make_pair ("0x97", ONE_HUNDRED_FIFTY_ONE),
                                                                                        std::make_pair ("0x98", ONE_HUNDRED_FIFTY_TWO),
                                                                                        std::make_pair ("0x99", ONE_HUNDRED_FIFTY_THREE),
                                                                                        std::make_pair ("0x9A", ONE_HUNDRED_FIFTY_FOUR),
                                                                                        std::make_pair ("0x9B", ONE_HUNDRED_FIFTY_FIVE),
                                                                                        std::make_pair ("0x9C", ONE_HUNDRED_FIFTY_SIX),
                                                                                        std::make_pair ("0x9D", ONE_HUNDRED_FIFTY_SEVEN),
                                                                                        std::make_pair ("0x9E", ONE_HUNDRED_FIFTY_EIGHT),
                                                                                        std::make_pair ("0x9F", ONE_HUNDRED_FIFTY_NINE),
                                                                                        std::make_pair ("0xA0", ONE_HUNDRED_SIXTY),
                                                                                        std::make_pair ("0xA1", ONE_HUNDRED_SIXTY_ONE),
                                                                                        std::make_pair ("0xA2", ONE_HUNDRED_SIXTY_TWO),
                                                                                        std::make_pair ("0xA3", ONE_HUNDRED_SIXTY_THREE),
                                                                                        std::make_pair ("0xA4", ONE_HUNDRED_SIXTY_FOUR),
                                                                                        std::make_pair ("0xA5", ONE_HUNDRED_SIXTY_FIVE),
                                                                                        std::make_pair ("0xA6", ONE_HUNDRED_SIXTY_SIX),
                                                                                        std::make_pair ("0xA7", ONE_HUNDRED_SIXTY_SEVEN),
                                                                                        std::make_pair ("0xA8", ONE_HUNDRED_SIXTY_EIGHT),
                                                                                        std::make_pair ("0xA9", ONE_HUNDRED_SIXTY_NINE),
                                                                                        std::make_pair ("0xAA", ONE_HUNDRED_SEVENTY),
                                                                                        std::make_pair ("0xAB", ONE_HUNDRED_SEVENTY_ONE),
                                                                                        std::make_pair ("0xAC", ONE_HUNDRED_SEVENTY_TWO),
                                                                                        std::make_pair ("0xAD", ONE_HUNDRED_SEVENTY_THREE),
                                                                                        std::make_pair ("0xAE", ONE_HUNDRED_SEVENTY_FOUR),
                                                                                        std::make_pair ("0xAF", ONE_HUNDRED_SEVENTY_FIVE),
                                                                                        std::make_pair ("0xB0", ONE_HUNDRED_SEVENTY_SIX),
                                                                                        std::make_pair ("0xB1", ONE_HUNDRED_SEVENTY_SEVEN),
                                                                                        std::make_pair ("0xB2", ONE_HUNDRED_SEVENTY_EIGHT),
                                                                                        std::make_pair ("0xB3", ONE_HUNDRED_SEVENTY_NINE),
                                                                                        std::make_pair ("0xB4", ONE_HUNDRED_EIGHTY),
                                                                                        std::make_pair ("0xB5", ONE_HUNDRED_EIGHTY_ONE),
                                                                                        std::make_pair ("0xB6", ONE_HUNDRED_EIGHTY_TWO),
                                                                                        std::make_pair ("0xB7", ONE_HUNDRED_EIGHTY_THREE),
                                                                                        std::make_pair ("0xB8", ONE_HUNDRED_EIGHTY_FOUR),
                                                                                        std::make_pair ("0xB9", ONE_HUNDRED_EIGHTY_FIVE),
                                                                                        std::make_pair ("0xBA", ONE_HUNDRED_EIGHTY_SIX),
                                                                                        std::make_pair ("0xBB", ONE_HUNDRED_EIGHTY_SEVEN),
                                                                                        std::make_pair ("0xBC", ONE_HUNDRED_EIGHTY_EIGHT),
                                                                                        std::make_pair ("0xBD", ONE_HUNDRED_EIGHTY_NINE),
                                                                                        std::make_pair ("0xBE", ONE_HUNDRED_NINTY),
                                                                                        std::make_pair ("0xBF", ONE_HUNDRED_NINTY_ONE),
                                                                                        std::make_pair ("0xC0", ONE_HUNDRED_NINTY_TWO),
                                                                                        std::make_pair ("0xC1", ONE_HUNDRED_NINTY_THREE),
                                                                                        std::make_pair ("0xC2", ONE_HUNDRED_NINTY_FOUR),
                                                                                        std::make_pair ("0xC3", ONE_HUNDRED_NINTY_FIVE),
                                                                                        std::make_pair ("0xC4", ONE_HUNDRED_NINTY_SIX),
                                                                                        std::make_pair ("0xC5", ONE_HUNDRED_NINTY_SEVEN),
                                                                                        std::make_pair ("0xC6", ONE_HUNDRED_NINTY_EIGHT),
                                                                                        std::make_pair ("0xC7", ONE_HUNDRED_NINTY_NINE),
                                                                                        std::make_pair ("0xC8", TWO_HUNDRED),
                                                                                        std::make_pair ("0xC9", TWO_HUNDRED_ONE),
                                                                                        std::make_pair ("0xCA", TWO_HUNDRED_TWO),
                                                                                        std::make_pair ("0xCB", TWO_HUNDRED_THREE),
                                                                                        std::make_pair ("0xCC", TWO_HUNDRED_FOUR),
                                                                                        std::make_pair ("0xCD", TWO_HUNDRED_FIVE),
                                                                                        std::make_pair ("0xCE", TWO_HUNDRED_SIX),
                                                                                        std::make_pair ("0xCF", TWO_HUNDRED_SEVEN),
                                                                                        std::make_pair ("0xD0", TWO_HUNDRED_EIGHT),
                                                                                        std::make_pair ("0xD1", TWO_HUNDRED_NINE),
                                                                                        std::make_pair ("0xD2", TWO_HUNDRED_TEN),
                                                                                        std::make_pair ("0xD3", TWO_HUNDRED_ELEVEN),
                                                                                        std::make_pair ("0xD4", TWO_HUNDRED_TWELVE),
                                                                                        std::make_pair ("0xD5", TWO_HUNDRED_THIRTEEN),
                                                                                        std::make_pair ("0xD6", TWO_HUNDRED_FOURTEEN),
                                                                                        std::make_pair ("0xD7", TWO_HUNDRED_FIFTEEN),
                                                                                        std::make_pair ("0xD8", TWO_HUNDRED_SIXTEEN),
                                                                                        std::make_pair ("0xD9", TWO_HUNDRED_SEVENTEEN),
                                                                                        std::make_pair ("0xDA", TWO_HUNDRED_EIGHTEEN),
                                                                                        std::make_pair ("0xDB", TWO_HUNDRED_NINETEEN),
                                                                                        std::make_pair ("0xDC", TWO_HUNDRED_TWENTY),
                                                                                        std::make_pair ("0xDD", TWO_HUNDRED_TWENTY_ONE),
                                                                                        std::make_pair ("0xDE", TWO_HUNDRED_TWENTY_TWO),
                                                                                        std::make_pair ("0xDF", TWO_HUNDRED_TWENTY_THREE),
                                                                                        std::make_pair ("0xE0", TWO_HUNDRED_TWENTY_FOUR),
                                                                                        std::make_pair ("0xE1", TWO_HUNDRED_TWENTY_FIVE),
                                                                                        std::make_pair ("0xE2", TWO_HUNDRED_TWENTY_SIX),
                                                                                        std::make_pair ("0xE3", TWO_HUNDRED_TWENTY_SEVEN),
                                                                                        std::make_pair ("0xE4", TWO_HUNDRED_TWENTY_EIGHT),
                                                                                        std::make_pair ("0xE5", TWO_HUNDRED_TWENTY_NINE),
                                                                                        std::make_pair ("0xE6", TWO_HUNDRED_THIRTY),
                                                                                        std::make_pair ("0xE7", TWO_HUNDRED_THIRTY_ONE),
                                                                                        std::make_pair ("0xE8", TWO_HUNDRED_THIRTY_TWO),
                                                                                        std::make_pair ("0xE9", TWO_HUNDRED_THIRTY_THREE),
                                                                                        std::make_pair ("0xEA", TWO_HUNDRED_THIRTY_FOUR),
                                                                                        std::make_pair ("0xEB", TWO_HUNDRED_THIRTY_FIVE),
                                                                                        std::make_pair ("0xEC", TWO_HUNDRED_THIRTY_SIX),
                                                                                        std::make_pair ("0xED", TWO_HUNDRED_THIRTY_SEVEN),
                                                                                        std::make_pair ("0xEE", TWO_HUNDRED_THIRTY_EIGHT),
                                                                                        std::make_pair ("0xEF", TWO_HUNDRED_THIRTY_NINE),
                                                                                        std::make_pair ("0xF0", TWO_HUNDRED_FORTY),
                                                                                        std::make_pair ("0xF1", TWO_HUNDRED_FORTY_ONE),
                                                                                        std::make_pair ("0xF2", TWO_HUNDRED_FORTY_TWO),
                                                                                        std::make_pair ("0xF3", TWO_HUNDRED_FORTY_THREE),
                                                                                        std::make_pair ("0xF4", TWO_HUNDRED_FORTY_FOUR),
                                                                                        std::make_pair ("0xF5", TWO_HUNDRED_FORTY_FIVE),
                                                                                        std::make_pair ("0xF6", TWO_HUNDRED_FORTY_SIX),
                                                                                        std::make_pair ("0xF7", TWO_HUNDRED_FORTY_SEVEN),
                                                                                        std::make_pair ("0xF8", TWO_HUNDRED_FORTY_EIGHT),
                                                                                        std::make_pair ("0xF9", TWO_HUNDRED_FORTY_NINE),
                                                                                        std::make_pair ("0xFA", TWO_HUNDRED_FIFTY),
                                                                                        std::make_pair ("0xFB", TWO_HUNDRED_FIFTY_ONE),
                                                                                        std::make_pair ("0xFC", TWO_HUNDRED_FIFTY_TWO),
                                                                                        std::make_pair ("0xFD", TWO_HUNDRED_FIFTY_THREE),
                                                                                        std::make_pair ("0xFE", TWO_HUNDRED_FIFTY_FOUR),
                                                                                        std::make_pair ("0xFF", TWO_HUNDRED_FIFTY_FIVE)
            };

            const std::array <std::string, TEN> Negative                           = { "0xn@",
                                                                                       "0xG,",
                                                                                       "0xgu",
                                                                                       "0xXy",
                                                                                       "0xyt",
                                                                                       "0xZr",
                                                                                       "0xl,",
                                                                                       "0x]w",
                                                                                       "0x/q",
                                                                                       "0x,k" };
        } HexInAsciToIntConversionResult;
};

///////////////////////////////////////////////////////////////////////////////
/////////////////////////////// END OF FILE ///////////////////////////////////
///////////////////////////////////////////////////////////////////////////////